### ISSUE TITLE
Weighings

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/democratic-collaboration#10]
Suggestion: add author's commit weighting, otherwise total is not achievable, as authors can't review their own PRs.

Second suggestion: require at least 1 reviewer, so 2 people will have seen the code.

**Comment by Somotaw** [comment]
they would
total is total eligable votes

:slightly_smiling_face:

**Comment by TooAngel** [comment]
I'm subtracting the PR authors weight from the total.

Second suggestion: I think the system keeps rolling and don't stop. I'm more trying to solve that code doesn't move forward. E.g. in tooangel/screeps if I'm not available for some weeks, nothing will happen.
If you are interested in some code you should do your review. If you don't review code can end up which you don't like, but you had the possibility ... (Get what I mean?)

**Comment by WhiteHalmos** [comment]
+1 These both sound like they've been covered. :)
