### ISSUE TITLE
Suggestion: Add optional REVIEWERS file

### ISSUE THREAD

**Issue by WhiteHalmos** [TooAngel/democratic-collaboration#20]
Rather than implicitly determining who should review pull requests, perhaps it's better to have a REVIEWERS file that lists who wants to review code out of all the collaborators.

Use case 1: Someone contributed in the past but no longer wants to or have time to contribute/review now. They can remove themselves from REVIEWERS.

Use case 2: New people who contribute just a couple times don't block the review process since they likely don't understand the code anyways.

Use case 3: Only experienced contributors review code, ensuring a higher code quality, and new contributors can add themselves to REVIEWERS when they feel ready instead of immediately whether they want to or not.

**Comment by WhiteHalmos** [comment]
Example: I would not add myself to REVIEWERS from this repository. ;)

**Comment by TooAngel** [comment]
:-) I guessed that you would will say it at some point in time.

I changed the summoning to `commits >= 10` https://github.com/TooAngel/democratic-collaboration/pull/19/files#diff-94ab7c76892f0032ee9ad040e3e8f207R62

So that not one time commited are summoned, I hope that is fine for you.

**Comment by WhiteHalmos** [comment]
That mostly works and is a good requirement, all reviewers must have contributed at least 10 commits.

I was thinking of something like a reviewer can flag "I'm not available for reviews right now" and not be counted in the total required nor be pinged.

Example: I'm getting busy now and won't have time for regular reviews, so I don't want to block PR progress even though I've contributed in the past or might have time in the future. :smile:

**Comment by TooAngel** [comment]
Would keep it like this, will work on some frontend for configuration options. Will close this issue now.
